### ISSUE TITLE
Bug: workflow fail to push image to docker hub

### ISSUE THREAD

**Issue by bap2pecs** [0xPolygon/cdk-validium-node#16]
The github workflow is broken due to missing username and password

<img width="1113" alt="image" src="https://github.com/0xPolygon/cdk-validium-node/assets/111917526/e0011f96-5330-4677-8c8c-c30035ab3926">

example run: https://github.com/0xPolygon/cdk-validium-node/actions/runs/5998016560

**Comment by arnaubennassar** [comment]
added missing secrets, should work now

**Comment by bap2pecs** [comment]
thanks @arnaubennassar! but I still don't see the image on https://hub.docker.com/u/hermeznetwork. I think you will need to trigger a re-run
